config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :answers, only: [:create]
  end

  resources :answers, except: [:create] do
    resources :comments, only: [:create]
  end

  resources :comments, except: [:create]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'questions#index'

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :text,  :presence => true

  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :text

  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :text,  :presence => true

  belongs_to :user
  has_many :answers, dependent: :destroy

  def time_since_creation
    time_since = ((Time.now - created_at)/60).round
    if time_since >= 60
      return "#{time_since / 60} hours and #{time_since % 60} minutes ago"
    end
    "#{time_since} minutes ago"
  end
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true
  validates_length_of :password, :in => 6..20, :on => :create

  has_many :questions
  has_many :answers
  has_many :comments
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def edit
    # @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    redirect_to @answer.question unless authorized?(@answer)
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user = current_user
    @answer.save
    redirect_to @question
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if authorized?(@answer)
      if @answer.update(answer_params)
        redirect_to @question
      else
        render 'edit'
      end
    else
      redirect_to @question
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if authorized?(@answer)
      @answer.destroy
    end
    redirect_to question_path(@question)
  end


  private
    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorized?

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authorized?(resource)
    current_user == resource.user
  end

  def require_login
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create]

  def index
    @questions = Question.all
    respond_to do |format|
      format.html
      format.json { render json: @questions }
    end
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
    redirect_to @question unless authorized?(@question)
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user if current_user
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    if authorized?(@question)
      if @question.update(question_params)
        redirect_to @question
      else
        render 'edit'
      end
    else
      redirect_to @question
    end
  end

  def destroy
    if authorized?(@question)
      @question.destroy
      redirect_to questions_path
    else
      redirect_to @question
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :text)
    end

    def find_question
      @question =Question.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to questions_path
    else
      @errors = ["The username and password you entered do not match"]
      render 'new'
    end
  end

  def destroy
    if logged_in?
      session.clear
    end
    redirect_to questions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for ([@question, @question.answers.build]) do |f| %>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
      <%= button_tag( :class => 'btn btn-default red darken-2') do %>
  Answer
<% end %>
  </p>

<% end %>

app/views/answers/edit.html.erb
<h2>Edit Answer</h2>

<%= form_for @answer do |f| %>
  <p>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.submit "Edit Answer"%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="nav-wrapper">
    <nav class="blue-grey lighten-4">
      <img src="https://s-media-cache-ak0.pinimg.com/originals/c3/eb/42/c3eb422708f7d7691f985f8541945197.png" style="width:75px;height:70px;">
      <ul class="right">
        <li ><%= link_to "Snack Overflow", questions_path, class: "white-text" %></li>
        <% if logged_in? %>
          <li><%= link_to "Ask a Question", new_question_path, class: "white-text" %></li>
          <li><%= link_to "#{current_user.username}", user_path(current_user), class: "white-text" %></li>
          <li><%= link_to "Log Out", session_path(session), method: :delete, class: "white-text" %></li>
        <% else %>
          <li><%= link_to "Create an Account", new_user_path, class: "white-text" %></li>
          <li><%= link_to "Log In", new_session_path, class: "white-text" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
 <div class="input-field col s12">
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s6">
    <%= f.label :title %><br>
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="input-field col s6">
    <%= f.label :question %><br>
    <%= f.text_area :text, autofocus: true,  class:"materialize-textarea" %>
  </div>

  <p>
    <%= button_tag( :class => 'btn btn-default red darken-2') do %>
  Submit
<% end %>
  </p>

<% end %>
</div>

app/views/questions/edit.html.erb
<h4 class='red-text text-darken-2'>Edit Your Question</h4>
<br/>
<br/>
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="container">
  <h2 class='red-text text-darken-2'>Snack Overflow</h2>

  <% if @questions %>
    <% @questions.each do |question| %>
      <table class="section">
        <tr>
          <td><strong><%= link_to "#{question.title}", question_path(question) %></strong><span> asked <%= question.time_since_creation %></span></td>
          <% if logged_in? && authorized?(question) %>
            <td><%= link_to 'Edit', edit_question_path(question) %></td>
            <td><%= link_to 'Destroy', question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      </table>
       <div class="divider"></div>
    <%end%>
  <%end%>
</div>
<%= react_component('App') %> 

app/views/questions/new.html.erb
<div>
  <h4 class='red-text text-darken-2'>Ask Question</h4>
<br/>
<br/>
  <%= render 'form' %>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
  <h2><%= @question.title %></h2>
  <p><%= @question.text %><span> asked by <%= @question.user.username %></span></p>
  <% if @question.answers %>
    <h3>Answers:</h3>
    <% @question.answers.each do |answer| %>
      <p><%= answer.text %><span>  - answered by <%= answer.user.username %>
        <% if authorized?(answer) %>
          <%= link_to 'Edit', edit_question_answer_path(answer.question, answer) %>
          <%= link_to "Delete", [answer.question, answer], method: :delete %>
        <% end %>
      </span></p>
    <% end %>
  <% end %>
  <%= render 'answers/form' %>
</div>

app/views/users/new.html.erb
<h4 class='red-text text-darken-2'>Create an Account</h4>
<br/>
<br/>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 <div class="input-field col s12">
<%= form_for :user, url: users_path do |f| %>
  <div class="input-field col s6">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
   <div class="input-field col s6">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
   <div class="input-field col s6">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <p>
     <%= button_tag( :class => 'btn btn-default red darken-2') do %>
  Register
<% end %>
  </p>
<% end %>
</div>